### ISSUE TITLE
Identity providers missing on login page

### ISSUE THREAD

**Issue by nr23730** [KohlbacherLab/dnpm-dip-portal#808]
On the admin page it is possible to add OAuth2 and OIDC identity providers. 
Unfortunately those cannot be used, because the login page currently does not list them.

**Comment by nr23730** [comment]
Thank you very much! However, even though this works I'm running into further issues this OIDC (Keycloak in that case):

* Cannot login unless admin privileges granted to all users on the identity provider.
* How is the "Roles" page for the identity provider supposed to work? I'd love to use client-roles defined in keycloak here.
* Users will appear multiple times in the list. Once with their username, once with their user ID in keycloak and multiple times with random(?) strings as username

**Comment by tada5hi** [comment]
@nr23730 You are very welcome!
Can you please open another issue for the 3 bullet points ?
